"""add product to category

Revision ID: d2cfdfdf5e7c
Revises: 7a2c20fedfab
Create Date: 2024-02-25 17:17:02.342146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cfdfdf5e7c'
down_revision = '7a2c20fedfab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['Category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Category_id')

    # ### end Alembic commands ###
